services:
  - type: web
    name: audio-transcribe-backend
    runtime: docker
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /health 